#!/bin/bash

curl --silent -X POST "http://127.0.0.1:5000/auth/login" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"email\": \"$1\",  \"password\": \"$2\"}" 2>&1 | jq '.access_token'
